OPENAI_API_KEY = "sk-proj-RTqSrqfjo6ZoHGJR6Q0uT3BlbkFJWGc08JyRr3thMfXcHUJp"
GROQ_API_KEY = "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"
LANGCHAIN_API_KEY = "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"
LANGCHAIN_TRACING_V2 = "true"